### ISSUE TITLE
Dependency Update and Print Function Fixes

### ISSUE THREAD

**Issue by dleiferives** [ltillmann/pdf-redactor#2]
The project at present does not run out of the box, there are errors with the printing and with the dependencies:

The fitz import is causing errors:
```
Traceback (most recent call last):
  File "pdf_redactor.py", line 3, in <module>
    import fitz  # PyMuPDF
  File "/mnt/c/school/phd/CMELON/tmp/venv/lib/python3.8/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
```
Additionally the program will not run due to print syntax:
```File "pdf_redactor.py", line 101
    print(f" |  Found {len(page_phone_numbers)} Phone Number{"" if len(page_phone_numbers)==1 else "s"} on Page {i+1}: {', '.join(str(p) for p in page_phone_numbers)}")
                                                                                                    ^
SyntaxError: invalid syntax
```

**Comment by dleiferives** [comment]
Fixed issues in pr https://github.com/ltillmann/pdf-redactor/pull/1 .
